pipeline:
  lint:
    image: akorn/luarocks:${TAG}
    commands:
      - apt-get update && apt-get upgrade -y
      - apt-get install unzip -y
      - luarocks install luacheck
      - luacheck --std max+busted hello.lua hello_spec.lua
  test:
    image: akorn/luarocks:${TAG}
    commands:
      - luarocks install busted
      - busted -o TAP .
    when:
          status: success
 
matrix:
  TAG:
    - lua5.1-alpine
    - lua5.2-alpine
    - lua5.3-alpine
    - luajit2.0-alpine
    - luajit2.1-alpine
