pipeline:
  lint:
    image: nickblah/luajit:2.0.5-luarocks-alpine
    commands:
      - luarocks install luacheck
      - luacheck --std max+busted hello.lua hello_spec.lua
  test:
    image: nickblah/luajit:2.0.5-luarocks-alpine
    commands:
      - luarocks install busted
      - busted -o TAP .
    when:
          status: success
