pipeline:
  lint:
    image: imolein/luarocks${LUA_VERSION}:latest
  settings:
    repo: octocat/hello-world
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    commands:
      - luarocks install luacheck
      - luacheck --std max+busted hello.lua hello_spec.lua
  test:
    image: imolein/luarocks${LUA_VERSION}:latest
  settings:
    repo: octocat/hello-world
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    commands:
      - luarocks install busted
      - busted -o TAP .
    when:
          status: success
 
matrix:
  LUA_VERSION:
    - 5.1
    - 5.2
    - 5.3
