pipeline:
  lint:
    image: akorn/luarocks${LUA_VERSION}:latest
    commands:
      - luarocks install luacheck
      - luacheck --std max+busted hello.lua hello_spec.lua
  test:
    image: akorn/luarocks${LUA_VERSION}:latest
    commands:
      - luarocks install busted
      - busted -o TAP .
    when:
          status: success
 
matrix:
  LUA_VERSION:
    - lua5.1-alpine
    - lua5.2-alpine
    - lua5.3-alpine
    - luajit2.0-alpine
    - luajit2.1-alpine
