pipeline:
  lint:
    image: imolein/luarocks:5.1
    commands:
      - luarocks install luacheck
      - luacheck --std max+busted hello.lua hello_spec.lua
  test:
    image: imolein/luarocks:5.1
    commands:
      - luarocks install busted
      - busted -o TAP .
    when:
          status: success
