pipeline:
  lint:
    image: abaez/luarocks:${TAG}
    commands:
      - apk update && apk upgrade
      - luarocks install luacheck
      - luarocks install busted
      - luacheck --std max+busted hello.lua hello_spec.lua
  test:
    image: abaez/luarocks:${TAG}
    commands:
#      - luarocks install busted
      - busted -o TAP .
    when:
          status: success
 
matrix:
  TAG:
    - 5.1
